repository: SwedbankPay/swedbank-pay-design-guide-jekyll-theme
plugins:
  - "jekyll-github-metadata"
  - jemoji
  - jekyll-material-icon-tag
  - "kramdown-plantuml"
# To include node_modules and other folders that are excluded by default:
# exclude: []
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true
    default_lang: html
    css_class: 'code-view'
    code_class: 'code-view-code'
    table_class: 'code-view-table'
    gutter_class: 'code-view-numbers'
    block:
      line_numbers: true
      start_line: 1
tipue_search:
  include:
    pages: true
opengraph:
  description: Swedbank Pay Design Guide theme for Jekyll
  image: /image1.png
design_guide:
  base_url: https://design.swedbankpay.com
  version: /feature/code-view
search:
  enabled: true
  url: /search
topbar:
  navigation:
  - url: /page1
    title: Top 1
  - url: /page2
    title: Top 2
google_analytics:
  tracking_id: false
defaults:
  - values:
      layout: default
